### ISSUE TITLE
Certain types of ZIP archives cause the remote read to stuck in an infinite loop

### ISSUE THREAD

**Issue by airatdev** [peret/http_zip#2]
It seems that EOCD block search gets stuck in an infinite loop [here](https://github.com/peret/http_zip/blob/master/lib/http_zip/parser/central_directory.rb#L71).

Example archive which triggers the issue: [DM_Sans.zip](https://github.com/user-attachments/files/16663013/DM_Sans.zip)

**Comment by peret** [comment]
Thank you for the report. I investigated a little and the issue seems to be two-fold: The first bug is that we run into an infinite loop if the EOCD-block cannot be detected. I pushed a fix for that to a new branch. The second issue is that apparently the code doesn't detect the EOCD block of this particular zip-file, although it seems to be valid. I'm going to investigate that next.

**Comment by peret** [comment]
@airatdev Should be fixed in 2.1.1. Let me know if there's still issues :+1:

**Comment by airatdev** [comment]
It works flawlessly now, thanks a lot for looking into this @peret! 💪
